import Foundation

/// Signing a picture this app drew, so it can be recognised again.
///
/// PlantUML does this for itself: its PNGs carry a `tEXt` chunk reading
/// "Generated by https://plantuml.com" and its SVGs a `<?plantuml …?>`
/// instruction, and `DiagramExport.refusal` reads that to tell a previous
/// export from somebody's own file with an unlucky name.
///
/// Mermaid signs nothing at all. `mermaid.render` hands back an SVG that says
/// only that it is a flowchart, and a canvas hands back bare pixels. So a
/// picture drawn from Mermaid would be indistinguishable from a screenshot, and
/// the refusal — which is exactly right and worth keeping — would fire on this
/// app's own output the second time somebody exported the same diagram.
///
/// The signature is deliberately the same string in both formats, so one search
/// through the first sixteen kilobytes finds either.
public enum DiagramStamp {
	/// What is written into the picture, and looked for when reading one back.
	///
	/// Not a URL and not a version. It answers exactly one question — did this
	/// app draw this file — and anything else in it would be something to keep
	/// up to date for no reader.
	public static let marker = "abydos-mermaid"

	// MARK: - SVG

	/// The instruction that goes at the top of a drawing.
	///
	/// A processing instruction rather than a comment or an attribute: it is
	/// what PlantUML uses for the same purpose, every SVG reader ignores one it
	/// does not know, and it cannot be mistaken for content the way a comment
	/// inside the document can.
	static let instruction = "<?\(marker)?>"

	/// Signs a drawing, if it is not signed already.
	///
	/// In front of the root element and after an XML declaration when there is
	/// one, because a declaration that is not the first thing in the file is not
	/// a declaration.
	public static func sign(svg: String) -> String {
		guard !svg.contains(instruction) else { return svg }
		guard let root = svg.range(of: "<svg") else { return instruction + "\n" + svg }
		return svg.replacingCharacters(in: root.lowerBound..<root.lowerBound, with: instruction + "\n")
	}

	// MARK: - PNG

	/// The eight bytes every PNG starts with.
	static let pngSignature: [UInt8] = [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]

	/// Signs a picture by putting a `tEXt` chunk into it.
	///
	/// Straight after `IHDR`, which is where the format says ancillary chunks
	/// may go and where PlantUML's own is. Anything that is not a PNG comes back
	/// unchanged rather than half-written: the caller's next act is to write
	/// this to somebody's repository.
	public static func sign(png data: Data) -> Data {
		let bytes = [UInt8](data)
		guard bytes.count > 8 + 12, Array(bytes.prefix(8)) == pngSignature else { return data }

		// The first chunk is IHDR, whose length is fixed at 13 — but read it
		// rather than assume it, since a file that is not shaped the way this
		// expects must be left alone instead of cut in half.
		let ihdrLength = Int(be32(bytes, at: 8))
		let afterIHDR = 8 + 4 + 4 + ihdrLength + 4
		guard afterIHDR <= bytes.count,
		      Array(bytes[12..<16]) == Array("IHDR".utf8)
		else { return data }

		var signed = Data(bytes[0..<afterIHDR])
		signed.append(chunk(type: "tEXt", payload: Data("Software\u{0}Abydos (\(marker))".utf8)))
		signed.append(Data(bytes[afterIHDR...]))
		return signed
	}

	/// One PNG chunk: length, type, data, and the CRC of the last two.
	static func chunk(type: String, payload: Data) -> Data {
		var out = Data()
		out.append(contentsOf: be32(UInt32(payload.count)))
		let body = Data(type.utf8) + payload
		out.append(body)
		out.append(contentsOf: be32(crc32(body)))
		return out
	}

	private static func be32(_ value: UInt32) -> [UInt8] {
		[UInt8(value >> 24 & 0xFF), UInt8(value >> 16 & 0xFF),
		 UInt8(value >> 8 & 0xFF), UInt8(value & 0xFF)]
	}

	private static func be32(_ bytes: [UInt8], at index: Int) -> UInt32 {
		(UInt32(bytes[index]) << 24) | (UInt32(bytes[index + 1]) << 16)
			| (UInt32(bytes[index + 2]) << 8) | UInt32(bytes[index + 3])
	}

	/// PNG's CRC-32, written out rather than linked.
	///
	/// It is the ordinary CRC-32, and zlib has it — but reaching zlib from Swift
	/// means a module map for one function, and this is nine lines.
	static func crc32(_ data: Data) -> UInt32 {
		var crc: UInt32 = 0xFFFF_FFFF
		for byte in data {
			crc ^= UInt32(byte)
			for _ in 0..<8 {
				crc = (crc & 1) == 1 ? (crc >> 1) ^ 0xEDB8_8320 : crc >> 1
			}
		}
		return crc ^ 0xFFFF_FFFF
	}
}
