import Foundation
import Testing
@testable import AbydosKit

/// What an export is called, what it refuses to write over, and how it knows a
/// diagram did not parse.
///
/// All of it decided without drawing anything: these are the rules that make an
/// export honest, and the drawing is the part a live test covers.
struct DiagramExportTests {
	// MARK: - What is in the file

	@Test func oneDiagramIsOneDiagram() {
		let found = DiagramExport.diagrams(in: "@startuml\nAlice -> Bob\n@enduml\n")
		#expect(found.count == 1)
		#expect(found[0].firstLine == 1)
	}

	/// A `.puml` may hold several, and where each begins is what makes a line
	/// number in the second one mean anything: PlantUML counts from the start of
	/// what it was given, which is the block rather than the file.
	@Test func severalDiagramsKeepTheirPlaceInTheFile() {
		let source = """
		@startuml
		Alice -> Bob
		@enduml

		@startuml
		Carol -> Dave
		@enduml
		"""
		let found = DiagramExport.diagrams(in: source)
		#expect(found.count == 2)
		#expect(found[0].firstLine == 1)
		#expect(found[1].firstLine == 5)
		#expect(found[1].text == "@startuml\nCarol -> Dave\n@enduml")
	}

	/// Other kinds of diagram start with other words, and all of them start with
	/// `@start` — which is the same test `PlantUML.hasDiagram` makes.
	@Test func mindmapsAndJsonCount() {
		#expect(DiagramExport.diagrams(in: "@startmindmap\n* one\n@endmindmap\n").count == 1)
		#expect(DiagramExport.diagrams(in: "@startjson\n{}\n@endjson\n").count == 1)
	}

	@Test func aFileWithNoDiagramInItHasNone() {
		#expect(DiagramExport.diagrams(in: "notes about the diagram\n").isEmpty)
		#expect(DiagramExport.diagrams(in: "").isEmpty)
	}

	/// Somebody halfway through typing one. PlantUML draws it, so it counts.
	@Test func anUnfinishedDiagramCounts() {
		let found = DiagramExport.diagrams(in: "@startuml\nAlice -> Bob\n")
		#expect(found.count == 1)
		#expect(found[0].firstLine == 1)
	}

	// MARK: - Where the pictures go

	@Test func onePictureIsNamedAfterTheFile() {
		let source = URL(fileURLWithPath: "/w/docs/diagram.puml")
		#expect(DiagramExport.destinations(for: source, format: .png, diagrams: 1)
			== [URL(fileURLWithPath: "/w/docs/diagram.png")])
		#expect(DiagramExport.destinations(for: source, format: .svg, diagrams: 1)
			== [URL(fileURLWithPath: "/w/docs/diagram.svg")])
	}

	/// The names PlantUML's own file output uses, so a project that already
	/// refers to `diagram_001.png` finds the same file here.
	@Test func severalPicturesAreNumberedAsPlantUMLNumbersThem() {
		let source = URL(fileURLWithPath: "/w/docs/diagram.puml")
		#expect(DiagramExport.destinations(for: source, format: .png, diagrams: 3).map(\.lastPathComponent)
			== ["diagram.png", "diagram_001.png", "diagram_002.png"])
	}

	/// The other extensions PlantUML recognises lose their own and gain the
	/// picture's, rather than becoming `diagram.wsd.png`.
	@Test func theSourcesExtensionIsReplaced() {
		let source = URL(fileURLWithPath: "/w/diagram.wsd")
		#expect(DiagramExport.destinations(for: source, format: .png, diagrams: 1)[0].lastPathComponent
			== "diagram.png")
	}

	// MARK: - What is already there

	/// A PNG PlantUML drew carries the sentence in a `tEXt` chunk; an SVG
	/// carries a `<?plantuml?>` instruction. Both are near the front.
	@Test func aPictureFromPlantUMLIsRecognised() {
		var png = Data([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A])
		png.append(Data("....tEXtcopyleft\0Generated by https://plantuml.com".utf8))
		#expect(DiagramExport.isDrawnByPlantUML(png))

		let svg = Data("<svg xmlns=\"http://www.w3.org/2000/svg\"><?plantuml 1.2026.6?></svg>".utf8)
		#expect(DiagramExport.isDrawnByPlantUML(svg))
	}

	@Test func somebodyElsesPictureIsNot() {
		let screenshot = Data([0x89, 0x50, 0x4E, 0x47]) + Data(repeating: 0x42, count: 4096)
		#expect(!DiagramExport.isDrawnByPlantUML(screenshot))
		#expect(!DiagramExport.isDrawnByPlantUML(Data()))
	}

	/// The whole of the collision rule: a previous export is replaced, because
	/// exporting twice is how anybody works; anything else stops the export with
	/// a sentence, because a file somebody made is not this feature's to destroy.
	@Test func aPreviousExportIsReplacedAndAStrangersFileIsNot() {
		let ours = Data("<svg><?plantuml 1.2026.6?></svg>".utf8)
		let theirs = Data(repeating: 0x42, count: 512)
		let destination = URL(fileURLWithPath: "/w/diagram.svg")

		#expect(DiagramExport.refusal(toWrite: [destination], reading: { _ in nil }) == nil)
		#expect(DiagramExport.refusal(toWrite: [destination], reading: { _ in ours }) == nil)

		let refused = DiagramExport.refusal(toWrite: [destination], reading: { _ in theirs })
		#expect(refused?.contains("diagram.svg") == true)
		// Not "not drawn by PlantUML" any more: the same rule now guards the
		// Mermaid export, which signs its own output rather than PlantUML's way.
		#expect(refused?.contains("was not drawn from a diagram") == true)
	}

	/// Every destination before any of them is drawn: finding out about the
	/// third one after two are written is the half-done state this avoids.
	@Test func everyDestinationIsCheckedBeforeAnythingIsDrawn() {
		let first = URL(fileURLWithPath: "/w/diagram.png")
		let second = URL(fileURLWithPath: "/w/diagram_001.png")
		let refused = DiagramExport.refusal(toWrite: [first, second], reading: { url in
			url == second ? Data(repeating: 0x42, count: 64) : nil
		})
		#expect(refused?.contains("diagram_001.png") == true)
	}

	// MARK: - A diagram that does not parse

	/// The server says so in headers of its own, with the line counted from one.
	@Test func theServersHeadersSayWhatIsWrong() throws {
		let fault = try #require(DiagramFault(
			errorHeader: "Syntax Error? (Assumed diagram type: sequence)", lineHeader: "3"
		))
		#expect(fault.line == 3)
		#expect(fault.sentence(for: "diagram.puml")
			== "diagram.puml line 3: Syntax Error? (Assumed diagram type: sequence)")

		// No header, no fault: a 400 that says nothing about the diagram is not
		// something to report about the diagram.
		#expect(DiagramFault(errorHeader: nil, lineHeader: "3") == nil)
		#expect(DiagramFault(errorHeader: "", lineHeader: nil) == nil)
	}

	/// `-pipe` prints three lines, after whatever the JVM had to say first, and
	/// counts the line from zero — where the server's header for the same
	/// diagram says three. Measured on two diagrams; added to here so that one
	/// export reports one number whichever route drew it.
	@Test func thePipesComplaintIsTheSameComplaint() throws {
		let said = """
		Aug 09, 2026 9:13:58 AM java.util.prefs.FileSystemPreferences$1 run
		INFO: Created user preferences directory.
		ERROR
		2
		Syntax Error? (Assumed diagram type: sequence)
		"""
		let fault = try #require(DiagramFault(standardError: said))
		#expect(fault.line == 3)
		#expect(fault.message == "Syntax Error? (Assumed diagram type: sequence)")
	}

	@Test func aQuietRunIsNotAFault() {
		#expect(DiagramFault(standardError: "") == nil)
		#expect(DiagramFault(standardError: "Picked up JAVA_TOOL_OPTIONS\n") == nil)
	}

	/// A line number in the second diagram of a file is about the file, not
	/// about the block PlantUML was handed.
	@Test func aLaterDiagramsLineIsCountedFromTheFile() {
		let fault = DiagramFault(message: "Syntax Error?", line: 2)
		#expect(fault.sentence(for: "diagram.puml", offset: 4) == "diagram.puml line 6: Syntax Error?")
	}

	@Test func aFaultWithNoLineStillSaysWhichFile() {
		let fault = DiagramFault(message: "Cannot find Graphviz.", line: nil)
		#expect(fault.sentence(for: "diagram.puml")
			== "diagram.puml could not be drawn: Cannot find Graphviz.")
	}
}
