#!/bin/bash
#
# Wraps the SPM executable into a real .app.
#
# The bundle is what gives ideai a Dock presence, a proper unified titlebar, and
# — importantly — a `Bundle.main.resourceURL` that the grammar query bundles can
# be found under at runtime.
#
# Usage: Scripts/bundle.sh [debug|release]   (default: release)

set -euo pipefail

cd "$(dirname "$0")/.."

CONFIG="${1:-release}"
APP="build/ideai.app"
CONTENTS="$APP/Contents"

echo "==> Building ($CONFIG)"
# Xcode's Swift rather than whatever is first on the PATH: a toolchain manager
# such as swiftly pins an older release, which cannot compile against a newer
# SDK and fails here with an error about Foundation rather than about ideai.
SWIFT=(xcrun swift)

"${SWIFT[@]}" build -c "$CONFIG"

BIN_DIR="$("${SWIFT[@]}" build -c "$CONFIG" --show-bin-path)"

echo "==> Assembling $APP"
rm -rf "$APP"
mkdir -p "$CONTENTS/MacOS" "$CONTENTS/Resources"

cp "$BIN_DIR/ideai" "$CONTENTS/MacOS/ideai"

# The Claude Code hook, which travels with the app but is its own binary:
# Claude runs it several times per tool call, and starting one that links
# AppKit and a syntax engine to read a line of JSON would be felt in every
# session on the machine.
cp "$BIN_DIR/ideai-hook" "$CONTENTS/MacOS/ideai-hook"

# Grammar query bundles. Without these every file opens uncoloured, so treat a
# missing set as a hard failure rather than shipping a broken app.
COUNT=0
for bundle in "$BIN_DIR"/*.bundle; do
	[ -e "$bundle" ] || continue
	cp -R "$bundle" "$CONTENTS/Resources/"
	COUNT=$((COUNT + 1))
done
if [ "$COUNT" -eq 0 ]; then
	echo "error: no resource bundles found in $BIN_DIR — grammars would not highlight" >&2
	exit 1
fi
echo "    copied $COUNT grammar bundles"

# GoSTL ships its shader as source and compiles it in its own Makefile, so a
# build that only asks SwiftPM for the library gets a bundle without the
# default.metallib the renderer looks for — and the 3D tab aborts on open.
# The shader sits at the root of the SwiftPM bundle, not under
# Contents/Resources — that layout is the one GoSTL's own installer produces.
#
# Written into the build directory's copy as well as the app's. `Bundle.module`
# resolves to the build path whenever it still exists, which it does on the
# machine that built the app, so shipping it only inside the .app leaves a
# developer running a viewer that cannot find its shaders.
GOSTL_SHADER=$(find "$CONTENTS/Resources" -name Shaders.metal -path "*GoSTL*" 2>/dev/null | head -1)
if [ -n "$GOSTL_SHADER" ]; then
	xcrun -sdk macosx metal -c "$GOSTL_SHADER" -o "$BIN_DIR/Shaders.air" \
		&& xcrun -sdk macosx metallib "$BIN_DIR/Shaders.air" -o "$BIN_DIR/default.metallib" \
		&& echo "    compiled the 3D viewer's shaders"

	if [ -f "$BIN_DIR/default.metallib" ]; then
		find "$CONTENTS/Resources" "$BIN_DIR" -type d -name "GoSTL_GoSTL.bundle" 2>/dev/null |
			while read -r target; do
				cp "$BIN_DIR/default.metallib" "$target/"
			done
	fi
fi

# Bundled fonts, registered at launch so powerline prompts render without the
# user installing anything.
if [ -d Resources/Fonts ]; then
	mkdir -p "$CONTENTS/Resources/Fonts"
	cp Resources/Fonts/*.ttf "$CONTENTS/Resources/Fonts/" 2>/dev/null || true
	cp Resources/Fonts/LICENSE-* "$CONTENTS/Resources/Fonts/" 2>/dev/null || true
fi

# The icon. Generated by Scripts/make-icon.py; regenerate after editing that.
if [ -f Resources/Icon/ideai.icns ]; then
	cp Resources/Icon/ideai.icns "$CONTENTS/Resources/"
else
	echo "    WARNING: no icon — run python3 Scripts/make-icon.py"
fi

# Third-party notices travel with the app, not just the repo.
if [ -f THIRD-PARTY-NOTICES.md ]; then
	cp THIRD-PARTY-NOTICES.md "$CONTENTS/Resources/" 
	echo "    bundled $(ls "$CONTENTS/Resources/Fonts"/*.ttf 2>/dev/null | wc -l | tr -d ' ') fonts"
fi

# The same Info.plist Xcode builds with, rather than a second copy of it that
# drifts: the bundle id and the version have to agree wherever the app is built.
cp Resources/Info.plist "$CONTENTS/Info.plist"

# Stamped with the commit it was built from, so "did my build actually get
# installed" is a question with an answer. `CFBundleVersion` is the build
# number, and the count of commits is one that only ever goes up.
BUILD=$(git rev-list --count HEAD 2>/dev/null || echo 0)
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
DIRTY=$(git diff --quiet 2>/dev/null || echo "+")
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD" "$CONTENTS/Info.plist" >/dev/null
/usr/libexec/PlistBuddy -c "Add :IdeaiCommit string $COMMIT$DIRTY" "$CONTENTS/Info.plist" >/dev/null
echo "    build $BUILD ($COMMIT$DIRTY)"

# A signature of some kind is required: macOS refuses to launch an unsigned
# bundle that was assembled by hand rather than by Xcode.
#
# A real certificate rather than ad-hoc wherever one exists, because macOS keys
# the Local Network privacy grant on the signing identity, and an ad-hoc
# signature has no team — its identity is the code directory hash, which is a
# different one after every build. The permission granted to yesterday's build
# therefore matches nothing today, and because the denial is inherited by every
# process the app spawns, a debugger or a program under test loses the LAN with
# EHOSTUNREACH — "connect: no route to host" — and no prompt to re-grant.
# `tccutil` cannot reset LocalNetwork, so the only way back is the System
# Settings pane, by hand, after each build. The Apple Development certificate
# keeps the identity stable across rebuilds and the grant stays granted.
IDENTITY="${SIGN_IDENTITY:-}"
if [ -z "$IDENTITY" ]; then
	if security find-identity -v -p codesigning | grep -q "Apple Development"; then
		IDENTITY="Apple Development"
	else
		IDENTITY="-"
		echo "    no Apple Development certificate: signing ad-hoc, so Local Network"
		echo "    access must be re-granted in System Settings after every build"
	fi
fi

if ! SIGN_OUT=$(codesign --force --deep --sign "$IDENTITY" "$APP" 2>&1); then
	echo "    warning: codesign with '$IDENTITY' failed; the app may not launch" >&2
	echo "$SIGN_OUT" | sed 's/^/    /' >&2
else
	echo "    signed with: $IDENTITY"
fi

echo "==> Done: $APP"
